version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
    restart: always
  api:
    image: api
    ports:
      - "50123:50123/udp"
    depends_on:
      - db
    environment:
      MRPC:BroadcastAddress: "192.168.255.255"
      ConnectionStrings:Database: Host=db;Username=postgres;Database=db;Password=verysecretpassword
    build: "api/"
  ui:
    image: ui
    environment:
      API_TARGET: api
    ports:
      - "80:80"
    depends_on:
      - api
    build: "ui/"