version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=verysecretpassword
    restart: always
    network_mode: host
  api:
    image: api
    depends_on:
      - db
    environment:
      MRPC:BroadcastAddress: "192.168.1.255"
      ConnectionStrings:Database: Host=localhost;Username=postgres;Database=db;Password=verysecretpassword
    build: "api/"
    network_mode: host
  ui:
    image: ui
    environment:
      API_TARGET: api
    depends_on:
      - api
    build: "ui/"
    network_mode: host
